-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 616c1ebd1898c91de9a0548866a59cbd9f4547f6
    hooks:
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E309']
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: flake8
        args: ['--exclude=node_modules']
